version: '3'

networks:
  elk:

volumes:
  elasticsearch:
    driver: local

services:
  elasticsearch:

    image: docker.elastic.co/elasticsearch/elasticsearch:8.8.0
    networks:
      elk: null
    ports:
    - 9200:9200
    environment:
      transport.host: 127.0.0.1
      cluster.name: "docker-cluster"
      network.host: 0.0.0.0
      xpack.security.enabled: false
      LOGSTASH_USERNAME: elkstack1
      LOGSTASH_PASSWORD: elkelk1
      KIBANA_USERNAME1: elkstack2
      KIBANA_PASSWORD1: elkelk2
    restart: unless-stopped
    volumes:
    #- elasticsearch:/usr/share/elasticsearch/data2:rw
    - elasticsearch:/usr/share/elasticsearch/data:rw


  kibana:
    depends_on:
    - elasticsearch
    image: docker.elastic.co/kibana/kibana:8.8.0
    networks:
      elk: null
    ports:
    - 5601:5601
    environment:
      KIBANA_USERNAME1: elkstack2
      KIBANA_PASSWORD1: elkelk2
    restart: unless-stopped


  logstash:
    image: docker.elastic.co/logstash/logstash:8.8.0
    depends_on:
    - elasticsearch
    networks:
      elk: null
    ports:
    - 9999:9999
    - 9898:9898 
    environment:
      LOGSTASH_USERNAME: elkstack1
      LOGSTASH_PASSWORD: elkelk1
    volumes:
      - C:/Users/IND-TOSHIBA/Desktop/elasticSearch/elk-docker/logstash/config/logstash.conf:/usr/share/logstash/pipeline/logstash2.conf
      